### PR TITLE
fix: containerd container lock delete stdout error msg

### PR DESCRIPTION
**Pull request by alejandroEsc**
**What problem does this PR solve?**:

**Which issue(s) does this PR fix?**:

* https://jira.d2iq.com/browse/D2IQ-87632

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by dkoshkin** [comment]
Are there other instances that needs to be fixed in the same way? e.g. `kubeadm` https://github.com/mesosphere/konvoy-image-builder/pull/287/files#diff-5f8572a1492839c754b58fc939b8c0ab5a0427a880a69e766a37cdb266ed0338R13

**Comment by alejandroEsc** [comment]
> Are there other instances that needs to be fixed in the same way? e.g. `kubeadm` https://github.com/mesosphere/konvoy-image-builder/pull/287/files#diff-5f8572a1492839c754b58fc939b8c0ab5a0427a880a69e766a37cdb266ed0338R13

good point, i havent checked, will do. Also is it ok to skip this step if stdout is not available? I would guess yes but I would like a confirmation.

**Comment by alejandroEsc** [comment]
@faiq I have a test and golint error out are these expected?

**Comment by faiq** [comment]
So I took a look at the COPS issue linked and it looks like there was an issue with KIB v1.9.1 and version lock the actual issue should have been resolved with the following commit https://github.com/mesosphere/konvoy-image-builder/commit/ebaba83028e79adf8fb295b26961a18a15e9be50 


This error message occurs during the first run of KIB on a machine because nothing is in the versionlock and it warns about it. 

It looks safe to merge to me to suppress the output, but in my opinion the COPS is no longer valid.

Regarding the failing OVA test, that happens on delete. It is unrelated. 

The lint failure is due to some bad config.

Reach out on slack if you need some more clarification on this.

**Comment by alejandroEsc** [comment]
> Regarding the failing OVA test, that happens on delete. It is unrelated.

Looks like that PR fixes these issues already. Feel free to close this and update the JIra ticket that you have a solution already. Do you need reviewers?

**Comment by faiq** [comment]
Closing after conversation.

**Pull request closed without merging**
