### PR TITLE
feat: bump kubernetes version to 1.24.4

### PR DESCRIPTION
**Pull request by supershal**
**What problem does this PR solve?**:
- Upgrades kubernetes version to 1.24.4

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Bump default kubernetes version to 1.24.4
```

### CODE REVIEW

**Comment by supershal** [comment]
The kubernetes version needs to be updated in two places. I will file followup PR to refactor the code to have only one variable in the code that represents kuebernetes version.

**Review by dkoshkin — APPROVED** [review]

**Review by faiq — APPROVED** [review]

**Comment by supershal** [comment]
RHEL 8.2 FIPS non-airgapped job is failing because of 
```rhel-8.2-fips: fatal: [default]: FAILED! => {"attempts": 5, "changed": false, "msg": "Failed to download metadata for repo 'kubernetes': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried", "rc": 1, "results": []}```

The cloud front cache needs to be updated for https://packages.d2iq.com/konvoy/stable/linux/repos/el/kubernetes-v1.24.4-fips . Once this cache is refreshed, the CI job should run successfully.

**Comment by supershal** [comment]
Azure RHEL 7 FIPs job failing because Azure is not able to delete public ip soon enough when packer tries to cleanup. This can be mostly flake because of Azure infra being slow.

**Comment by dkoshkin** [comment]
> RHEL 8.2 FIPS non-airgapped job is failing because of `rhel-8.2-fips: fatal: [default]: FAILED! => {"attempts": 5, "changed": false, "msg": "Failed to download metadata for repo 'kubernetes': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried", "rc": 1, "results": []}`
> 
> The cloud front cache needs to be updated for https://packages.d2iq.com/konvoy/stable/linux/repos/el/kubernetes-v1.24.4-fips . Once this cache is refreshed, the CI job should run successfully.

I think for that one its the sync job that takes the packages from the staging bucket and promotes it to the prod bucket https://github.com/mesosphere/docker-repo-sync/blob/d8958f1b25df35ffd863a7f5a4aa20792afe8ef9/sync.sh#L15

**Pull request merged**
