### PR TITLE
feat: bump Containerd patch release 1.7.22

### PR DESCRIPTION
**Pull request by SandhyaRavi2403**
**What problem does this PR solve?**:
Updates to latest Containerd patch release https://github.com/containerd/containerd/releases/tag/v1.7.22

**Which issue(s) does this PR fix?**:
https://jira.nutanix.com/browse/NCN-102515

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by dkoshkin** [comment]
The e2e tests failed because of a [missing pause image](https://github.com/mesosphere/konvoy-image-builder/actions/runs/11019305973/job/30601709711?pr=1183#step:9:3295) 

Made the changes in https://github.com/mesosphere/dkp-release/pull/144 to include the correct image.

Please rebuild the Kubernetes packages with the above changes and create a stacked PR on this one to bump the Kubernetes version. We'll need both Containerd and Kubernetes changes for the air-gapped tests to work.

**Comment by dkoshkin** [comment]
@SandhyaRavi2403 please also change the commit message to be `feat: ...`

**Comment by SandhyaRavi2403** [comment]
> The e2e tests failed because of a [missing pause image](https://github.com/mesosphere/konvoy-image-builder/actions/runs/11019305973/job/30601709711?pr=1183#step:9:3295)
> 
> Made the changes in [mesosphere/dkp-release#144](https://github.com/mesosphere/dkp-release/pull/144) to include the correct image. I've rebuilt the Kubernetes packages [here](https://github.com/mesosphere/dkp-release/actions/workflows/build-chain.yaml) with the above changes.
> 
> Please create a stacked PR on this one to bump the Kubernetes version, we'll need both Containerd and Kubernetes changes for the air-gapped tests to work.

@dkoshkin 
bump the k8s version, do you mean having the changes of https://github.com/mesosphere/konvoy-image-builder/pull/1180/files in this PR.

**Comment by dkoshkin** [comment]
The changes here won't pass the e2e tests without https://github.com/mesosphere/konvoy-image-builder/pull/1188.

The other PR used this branch as its base branch and the tests there passed, going to merge this.

**Review by dkoshkin — APPROVED** [review]

**Pull request merged**
