### PR TITLE
ci: bump CAPPP on successful release jobs

### PR DESCRIPTION
**Pull request by supershal**
**What problem does this PR solve?**:
Prevents CAPPP bump in case of KIB release failure

### CODE REVIEW

**Review by faiq — COMMENTED** [review]
i dont think it needs sign binary here

**Comment by supershal** [comment]
> i dont think it needs sign binary here

Agree. The CAPPP bump does not need signed binary job technically. However in my opinion, the KIB release should not considered successful if all steps, including signing binary, completes successfully. IMHO, bumping CAPPP needed only on successful release.

PS: slack notification needed for successful/failed release job. I will file separate PR for that.

**Review by dkoshkin — APPROVED** [review]

**Comment by faiq** [comment]
We can rerun the sign binary step separately. The two things are not related so it should not block the release

**Comment by dkoshkin** [comment]
@faiq so its possible to trigger the MacOS signing job if it fails without rerunning the rest of the job?
Would that be the workflow we want or would we instead want to rerun the whole release job?

**Review by faiq — APPROVED** [review]

**Pull request merged**
