### PR TITLE
adds installation of nvidia-container-runtime

### PR DESCRIPTION
**Pull request by tillt**

### CODE REVIEW

**Comment by tillt** [comment]
Used this:
```
[...]
    centos-7-nvidia: TASK [gpu : Install nvidia-container-tools] ************************************
    centos-7-nvidia: changed: [default]
    centos-7-nvidia:
    centos-7-nvidia: TASK [gpu : Install nvidia-container-runtime] **********************************
    centos-7-nvidia: changed: [default]
[...]
--> centos-7-nvidia: AMIs were created:
us-west-2: ami-04153a53d677d3a55
```

Then installed a konvoy2 cluster and kommander2 services on top of this without any issues. 

```
$ ./aws-up.sh
+ KONVOY=dist/konvoy_linux_amd64/konvoy
+ AMI_ID=ami-04153a53d677d3a55
+ INSTANCE_TYPE=p2.xlarge
[...]
Kommander 2 is now running in the cluster.
[...]
```

**Review by jongiddy — APPROVED** [review]

**Comment by tillt** [comment]
Ran the molecule GPU tests against it:
```
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/till
plugins: testinfra-6.4.0
collected 25 items

molecule/ec2_gpu/tests/test_default.py .........................         [100%]

============================= 25 passed in 39.75s ==============================
```

**Comment by tillt** [comment]
I believe we are seeing the same problem @jongiddy identified at https://github.com/mesosphere/konvoy-image-builder/pull/37#issuecomment-888369012

**Comment by tillt** [comment]
@dlipovetsky I won't leave such useless PR descriptions again, sorry.

**Pull request merged**
