### PR TITLE
ansible: configure proxy support

### PR DESCRIPTION
**Pull request by jkoelker**
Configures `[HTTP|HTTPS|NO]_PROXY` support for `containerd` and `kubelet`.

Rebased atop #44

### CODE REVIEW

**Review by dkoshkin — COMMENTED** [review]
Does KIB already set the proxy vars when downloading OS packages, docker images and other binaries?

**Comment by jkoelker** [comment]
> Does KIB already set the proxy vars when downloading OS packages, docker images and other binaries?

Not during the image build phase, I can totes add that in to the remote exe env, (https://github.com/mesosphere/konvoy-image-builder/blob/main/pkg/packer/manifests/aws/packer.json.tmpl#L89-L129), locally the exec'd `packer` will respect the env vars. 

Presumably they could be a different set too, so I guess having them be a set of specific vars (`provisioner_http_proxy`, et. al) and then falling back to the runtime (`http_proxy`) vars would be needed as well.

**Comment by jkoelker** [comment]
Tested Centos7 and I was a bit too eager above to suggest allowing separate proxies. The issue is that during the build we start containerd (with its http dropin) and pull the images, so to have ami build time proxy != runtime proxy would require some gymnastics (totally doable though with another dropin to override the override, and a post task to clean it up before exiting).

But I'm getting stron YAGNI vibes from that, so until it becomes a req to have them separate I suggest we just roll with one set.

The override file for testing was:

```yaml
---
http_proxy: http://my.proxy.url:8888
https_proxy: http://my.proxy.url:8888
no_proxy: yahoo.com
```

**Comment by jkoelker** [comment]
Refactored to use an `EnvironmentFile` which is removed after the run. Konvoy2 will write the file via `KubeadmConfigSpec.Files` at provision time to specify the runtime proxy if needed.

**Comment by jkoelker** [comment]
*NOTE* I don't have access to TeamCity so I can't see why it failed. I suspect its being flakey as its has randomly failed when manual testing has passed. If someone has access to re-run it or grab the logs for me I'd appreciate it.

**Comment by jongiddy** [comment]
The test is failing with
```
    flatcar-2905.2.0: TASK [packages : Fail if pre-installed containerd version does not match for Flatcar] ***
    flatcar-2905.2.0: fatal: [default]: FAILED! => {"changed": true, "cmd": "containerd --version | cut -d\\  -f 3", "delta": "0:00:00.038818", "end": "2021-07-28 14:35:06.568745", "failed_when_result": true, "rc": 0, "start": "2021-07-28 14:35:06.529927", "stderr": "", "stderr_lines": [], "stdout": "1.5.4", "stdout_lines": ["1.5.4"]}
    flatcar-2905.2.0:
    flatcar-2905.2.0: PLAY RECAP *********************************************************************
    flatcar-2905.2.0: default                    : ok=19   changed=15   unreachable=0    failed=1    skipped=47   rescued=0    ignored=0
    flatcar-2905.2.0:
==> flatcar-2905.2.0: Provisioning step had errors: Running the cleanup provisioner, if present...
==> flatcar-2905.2.0: Terminating the source AWS instance...
==> flatcar-2905.2.0: Cleaning up any extra volumes...
==> flatcar-2905.2.0: No volumes to clean up, skipping
==> flatcar-2905.2.0: Deleting temporary security group...
==> flatcar-2905.2.0: Deleting temporary keypair...
Build 'flatcar-2905.2.0' errored after 5 minutes 33 seconds: Error executing Ansible: Non-zero exit status: exit status 2
```
but this also fails on `main` when I run (following MAWS setup) using
```bash
#!/bin/bash

set -e -x

eval "$(python3 hack/setup_environment.py)"

rm .docker-mesosphere.konvoy-image-builder.latest-devkit || true

make devkit.run WHAT='make flatcar'
```

**Comment by jongiddy** [comment]
With a re-run of the test, it looks like SuSE is sometimes the cause of the failure:
```
16:22:26
      sles-15-nvidia: TASK [gpu : Install Nvidia drivers] ********************************************
16:22:27
      sles-15-nvidia: fatal: [default]: FAILED! => {"changed": false, "cmd": ["/usr/bin/zypper", "--quiet", "--non-interactive", "--xmlout", "install", "--type", "package", "--auto-agree-with-licenses", "--no-recommends", "--", "+cuda-drivers-460"], "msg": "Zypper run command failed with return code 4.", "rc": 4, "stderr": "", "stderr_lines": [], "stdout": "<?xml version='1.0'?>\n<stream>\n<prompt id=\"1\">\n<description>Problem: nothing provides &apos;libvdpau1&apos; needed by the to be installed x11-video-nvidiaG05-460.91.03-0.x86_64\n Solution 1: do not install cuda-drivers-460-460.91.03-1.x86_64\n Solution 2: break x11-video-nvidiaG05-460.91.03-0.x86_64 by ignoring some of its dependencies\n</description>\n<text>Choose from above solutions by number or cancel</text>\n<option value=\"1\" desc=\"Choose solution 1\"/>\n<option value=\"2\" desc=\"Choose solution 2\"/>\n<option default=\"1\" value=\"c\" desc=\"Choose no solution and cancel.\"/>\n<option value=\"d\" desc=\"Toggle show detailed conflict information.\"/>\n</prompt>\n</stream>\n", "stdout_lines": ["<?xml version='1.0'?>", "<stream>", "<prompt id=\"1\">", "<description>Problem: nothing provides &apos;libvdpau1&apos; needed by the to be installed x11-video-nvidiaG05-460.91.03-0.x86_64", " Solution 1: do not install cuda-drivers-460-460.91.03-1.x86_64", " Solution 2: break x11-video-nvidiaG05-460.91.03-0.x86_64 by ignoring some of its dependencies", "</description>", "<text>Choose from above solutions by number or cancel</text>", "<option value=\"1\" desc=\"Choose solution 1\"/>", "<option value=\"2\" desc=\"Choose solution 2\"/>", "<option default=\"1\" value=\"c\" desc=\"Choose no solution and cancel.\"/>", "<option value=\"d\" desc=\"Toggle show detailed conflict information.\"/>", "</prompt>", "</stream>"]}
16:22:27
      sles-15-nvidia:
16:22:27
      sles-15-nvidia: RUNNING HANDLER [packages : reload systemd] ************************************
16:22:27
      sles-15-nvidia:
16:22:27
      sles-15-nvidia: RUNNING HANDLER [packages : restart containerd] ********************************
16:22:27
      sles-15-nvidia:
16:22:27
      sles-15-nvidia: RUNNING HANDLER [packages : restart kubelet] ***********************************
16:22:27
      sles-15-nvidia:
16:22:27
      sles-15-nvidia: PLAY RECAP *********************************************************************
16:22:27
      sles-15-nvidia: default                    : ok=30   changed=21   unreachable=0    failed=1    skipped=52   rescued=0    ignored=0
16:22:27
      sles-15-nvidia:
16:22:27
  ==> sles-15-nvidia: Provisioning step had errors: Running the cleanup provisioner, if present...
16:22:27
  ==> sles-15-nvidia: Terminating the source AWS instance...
16:23:13
  ==> sles-15-nvidia: Cleaning up any extra volumes...
16:23:13
  ==> sles-15-nvidia: No volumes to clean up, skipping
16:23:13
  ==> sles-15-nvidia: Deleting temporary security group...
16:23:14
  ==> sles-15-nvidia: Deleting temporary keypair...
16:23:14
  Build 'sles-15-nvidia' errored after 3 minutes 22 seconds: Error executing Ansible: Non-zero exit status: exit status 2
```

**Review by dkoshkin — APPROVED** [review]

**Review by jongiddy — APPROVED** [review]
Thanks! Dealing with proxy variables can be a tricky task.

**Pull request merged**
