### PR TITLE
feat: Upgrade NVIDIA GPU drivers to 470.x 

### PR DESCRIPTION
**Pull request by tillt**
https://jira.d2iq.com/browse/D2IQ-79232

### CODE REVIEW

**Comment by tillt** [comment]
on centos7.9 this installs the following:
```
[...]
Sep 20 20:37:35 ip-172-31-80-203.ec2.internal yum[20642]: Installed: 3:nvidia-driver-branch-470-libs-470.57.02-1.el7.x86_64
Sep 20 20:37:35 ip-172-31-80-203.ec2.internal yum[20642]: Installed: 3:nvidia-driver-branch-470-NVML-470.57.02-1.el7.x86_64
Sep 20 20:37:35 ip-172-31-80-203.ec2.internal yum[20642]: Installed: 3:nvidia-driver-branch-470-devel-470.57.02-1.el7.x86_64
Sep 20 20:37:35 ip-172-31-80-203.ec2.internal yum[20642]: Installed: 3:nvidia-driver-branch-470-NvFBCOpenGL-470.57.02-1.el7.x86_64
Sep 20 20:37:40 ip-172-31-80-203.ec2.internal yum[20642]: Installed: 3:nvidia-driver-branch-470-cuda-libs-470.57.02-1.el7.x86_64
Sep 20 20:37:40 ip-172-31-80-203.ec2.internal yum[20642]: Installed: 3:nvidia-modprobe-branch-470-470.57.02-1.el7.x86_64
Sep 20 20:37:40 ip-172-31-80-203.ec2.internal yum[20642]: Installed: 3:nvidia-xconfig-branch-470-470.57.02-1.el7.x86_64
Sep 20 20:37:40 ip-172-31-80-203.ec2.internal groupadd[20795]: group added to /etc/group: name=nvidia-persistenced, GID=994
Sep 20 20:37:40 ip-172-31-80-203.ec2.internal groupadd[20795]: group added to /etc/gshadow: name=nvidia-persistenced
Sep 20 20:37:40 ip-172-31-80-203.ec2.internal groupadd[20795]: new group: name=nvidia-persistenced, GID=994
Sep 20 20:37:40 ip-172-31-80-203.ec2.internal useradd[20800]: new user: name=nvidia-persistenced, UID=997, GID=994, home=/var/run/nvidia-persistenced, shell=/sbin/nologin
Sep 20 20:37:41 ip-172-31-80-203.ec2.internal systemd[1]: Reloading.
Sep 20 20:37:41 ip-172-31-80-203.ec2.internal yum[20642]: Installed: 3:nvidia-persistenced-branch-470-470.57.02-1.el7.x86_64
Sep 20 20:37:41 ip-172-31-80-203.ec2.internal yum[20642]: Installed: 3:nvidia-driver-branch-470-cuda-470.57.02-1.el7.x86_64
```

and then loads the installed modules successfully
```
[...]
Sep 20 20:41:04 ip-172-31-80-203.ec2.internal kernel: nvidia: module verification failed: signature and/or required key missing - tainting kernel
Sep 20 20:41:04 ip-172-31-80-203.ec2.internal kernel: nvidia-nvlink: Nvlink Core is being initialized, major device number 243
Sep 20 20:41:04 ip-172-31-80-203.ec2.internal kernel: NVRM: loading NVIDIA UNIX x86_64 Kernel Module  470.57.02  Tue Jul 13 16:14:05 UTC 2021
Sep 20 20:41:04 ip-172-31-80-203.ec2.internal kernel: nvidia-uvm: Loaded the UVM driver, major device number 241.
Sep 20 20:41:04 ip-172-31-80-203.ec2.internal kernel: nvidia-modeset: Loading NVIDIA Kernel Mode Setting Driver for UNIX platforms  470.57.02  Tue Jul 13 16:06:24 UTC 2021
Sep 20 20:41:04 ip-172-31-80-203.ec2.internal kernel: [drm] [nvidia-drm] [GPU ID 0x0000001e] Loading driver
Sep 20 20:41:04 ip-172-31-80-203.ec2.internal kernel: [drm] Initialized nvidia-drm 0.0.0 20160202 for 0000:00:1e.0 on minor 1
Sep 20 20:41:04 ip-172-31-80-203.ec2.internal yum[20642]: Installed: 3:kmod-nvidia-latest-dkms-470.57.02-1.el7.x86_64
Sep 20 20:41:06 ip-172-31-80-203.ec2.internal yum[20642]: Installed: 3:nvidia-driver-branch-470-470.57.02-1.el7.x86_64
```

**Comment by tillt** [comment]
running nvidia-smi on the host:
```
$ nvidia-smi
Mon Sep 20 20:57:41 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   64C    P0    61W / 149W |      0MiB / 11441MiB |     68%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by tillt** [comment]
Ran the molecule GPU suite against this PR while disabling flatcar:

```
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/till
plugins: testinfra-6.4.0
collected 25 items

molecule/ec2_gpu/tests/test_default.py .........................         [100%]
```

5 tests per distro - 5 distros tested = 25 tests -- succeeded 100%
- centos 7.8
- centos 7.9
- rhel 7.9
- rhel 8.4
- suse 15

That means we have the 470.x drivers available for all of those and they install and validate properly.

**Review by mhrabovcin — APPROVED** [review]

**Review by jongiddy — APPROVED** [review]
`+4 −22 ` Nice!

**Pull request merged**
