### PR TITLE
feat: bump k8s to 1.22.8

### PR DESCRIPTION
**Pull request by jkoelker**
**What problem does this PR solve?**:

* Bumps k8s to 1.22.4
* Removed old note (repository promotion job now exists)

**Which issue(s) does this PR fix?**:

* https://jira.d2iq.com/browse/D2IQ-81792

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Feature: Default to Kubernetes 1.22.7
```

### CODE REVIEW

**Comment by jkoelker** [comment]
Waiting for the staging to prod job to sync ubuntu:focal, then the ubuntu-20 build will succeed as well.

**Comment by jkoelker** [comment]
After this merges, I'd like to release `1.5.0` so we can bump it in konvoy2.

**Comment by dlipovetsky** [comment]
From standup:
- Changes more than the default Kubernetes version. The etcd and pause versions are "coupled" to the Kubernetes version.
- @joejulian suggests defining version groups, based on the Kubernetes patch version. @dlipovetsky and @dkoshkin agree. 
- @dlipovetsky says that upstream treats these components as coupled; e..g, the etcd and pause versions are bumped upstream in Kubernetes patch versions.

We're asking for new functionality (version groups, based on Kubernetes patch version) in a separate PR. Once that PR merges, this PR can use that functionality)

**Review by tillt — APPROVED** [review]

**Comment by dlipovetsky** [comment]
We're working on changes for DKP 2.1.1. Let's not merge this until after, please.

**Comment by joejulian** [comment]
rebased

**Comment by joejulian** [comment]
... and reworded commits for `releaseplease`

**Comment by jkoelker** [comment]
Note the `E2E RHEL 8 FIPS (Konvoy Image Builder)` build will fail until we have fips builds for 1.22.4/5

**Comment by jkoelker** [comment]
I have successfully build a cluster with 1.22.4 images:

```
$ kubectl --kubeconfig jkoelker-aws-cluster.conf version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"archive", BuildDate:"2022-01-05T21:51:35Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:42:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by dlipovetsky** [comment]
From standup:

Everything is ready, except for FIPS. @joejulian is working on the FIPS portion. Once that's ready, we can merge, and then re-run tests and merge https://github.com/mesosphere/konvoy2/pull/932.

**Comment by dlipovetsky** [comment]
From standup: Although the other tests pass, we prefer to wait to merge this until FIPS is ready.

**Comment by joejulian** [comment]
@jkoelker There are repos that are now specific to the k8s version available. Do you want to make the changes to this in order to use them?

https://packages.d2iq.com/konvoy/stable/linux/repos/el/kubernetes-v1.22.7-nokmem/x86_64/

**Comment by joejulian** [comment]
rebased

**Review by joejulian — APPROVED** [review]

**Comment by joejulian** [comment]
All the required checks are passing.

**Review by dkoshkin — APPROVED** [review]

**Pull request merged**
