### PR TITLE
chore: make override offline file for aws consistent

### PR DESCRIPTION
**Pull request by faiq**
**What problem does this PR solve?**:
`make packer-aws-offline-override.yaml` previously did nothing. this should fix it 

**Which issue(s) does this PR fix?**:

* https://jira.d2iq.com/browse/D2IQ-NUMBER

**Special notes for your reviewer**:
Please run: 
```
 make packer-aws-offline-override.yaml
 cat packer-aws-offline-override.yaml
 ```
 on the main branch and this branch and see if things changed. 

In between switching do `make infra.aws.destroy` 

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by dkoshkin** [comment]
This only the older bash script based e2e right?

**Comment by dkoshkin** [comment]
Does this mean we weren't running the AWS tests in air-gapped?

**Comment by supershal** [comment]
I was able to get the infra references populated in the `packer-aws-offline-override.yaml` file when running `make packer-aws-offline-override.yaml` from main branch.

**Comment by alejandroEsc** [comment]
> I was able to get the infra references populated in the `packer-aws-offline-override.yaml` file when running `make packer-aws-offline-override.yaml` from main branch.

same here!

**Comment by faiq** [comment]
Ok this is good news i'll `make clean` and try agian

**Comment by faiq** [comment]
This seems to have been an issue local to me. 

I think this PR could still be helpful because it clears up names, but the e2e tests were working fine. I'll change the title to chore

**Review by supershal — APPROVED** [review]

**Pull request merged**
