### PR TITLE
feat: Change default containerd version to 1.4.13

### PR DESCRIPTION
**Pull request by dlipovetsky**
**What problem does this PR solve?**:

**Which issue(s) does this PR fix?**:

* https://jira.d2iq.com/browse/D2IQ-86415

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by faiq** [comment]
We need to build the new packages first before this can be merged in.... but that breaks the other ones :/

**Review by alejandroEsc — APPROVED** [review]
lgtm

**Comment by alejandroEsc** [comment]
@faiq what can we do to help make progress

**Comment by faiq** [comment]
it looks like we can close in favor of https://github.com/mesosphere/konvoy-image-builder/pull/329/files#diff-49290b023deb6a179994bf74f44f0a48ad353968ff9bc1b278947410bf49ae58

**Pull request closed without merging**
